#!/usr/bin/env python3
#
# Show sorted listing of the top 10 users who made changes to Gentoo bugzilla
# in the last week.

import collections
import datetime

from dateutil.relativedelta import relativedelta
from itertools import chain

from bite import get_service

today = datetime.datetime.utcnow()
previous = today + relativedelta(weeks=-1)

bugz = get_service('gentoo')
params = {}

params['status'] = ['all']
params['modified'] = previous
params['fields'] = ['id']
bugs = [bug.id for bug in bugz.search(params=params)]
comments = bugz.comments(ids=bugs, created=previous)
changes = bugz.changes(ids=bugs)


def filter_changes(change_list):
    for bug_changes in change_list:
        for change in bug_changes:
            if change.created.replace(tzinfo=None) > previous:
                yield change.creator.partition('@')[0]


changes = chain(comments, changes)
c = collections.Counter(filter_changes(changes))
for user, i in c.most_common(10):
    print(f'{i}: {user}')
